### ISSUE TITLE
Forge OrgDb package 

### ISSUE THREAD

**Issue by imalsoft9** [Bioconductor/AnnotationForge#16]
I need to create annotation package like (org.Hs.eg.db) for two organisms:
1-Galleria mellonella ASM364042v2
2-Madurella mycetomatis ASM127576v2\
Both genomes are assembled in scaffolds level
For the Galleria Mellonella there is  org.Galleria_mellonella.eg.sqlite in  AnnotationHub library but not  for the Madurella Mycetomatis.  I appreciate if you give guidelines or point to resource that I can follow to create OrgDb for the two genomes. the purpose was to use the OrgDb for gene set enrichment analysis.

**Comment by lshep** [comment]
There are two AnnotationForge functions for creating your own OrgDb.  Please check out `AnnotationForge::makeOrgPackage`  and/or  `AnnotationForge::makeOrgPackageFromNCBI`.  If you run into additional issues I highly suggest posting to the bioconductor support site instead of github issues.  The support site reaches the larger community base that might have additional solutions and faster attention.  Github issues more for reporting coding errors/bugs that need correcting.  support.bioconductor.org  Cheers!
