### ISSUE TITLE
Error when running makeOrgPackage (unable to Populate gene_info table) 

### ISSUE THREAD

**Issue by C2051** [Bioconductor/AnnotationForge#39]
This is my command:
makeOrgPackage(gene_info=gene_info, go=gene2go, ko=koterms,  pathway=gene2pathway, version="0.0.1", maintainer='wangdan <1114678784@qq.com>', author='wangdan <1114678784@qq.com>',outputDir="./output", tax_id="13055", genus="Chamaenerion", species="angustifolium",goTable="go")
        And I got this error:
Populating genes table:
genes table filled
Populating gene_info table:
Error: NOT NULL constraint failed: gene_info.GENENAME
        And here are the files I used. I don't know why  did this happened. I would very thank you if you can help me to solve this problem.
> head(gene2pathway)
               GID Pathway
1 evm.model.Chr1.1 ko03420
2 evm.model.Chr1.1 ko03430
3 evm.model.Chr1.1 ko03400
4 evm.model.Chr1.2 ko00910
5 evm.model.Chr1.2 ko00250
6 evm.model.Chr1.2 ko00220
> head(gene_info)
               GID       GENENAME
1 evm.model.Chr1.1     EKX90894.1
2 evm.model.Chr1.2     AGA29415.1
3 evm.model.Chr1.3 XP_004235208.1
4 evm.model.Chr1.4     KHG14627.1
5 evm.model.Chr1.5 XP_011626953.1
6 evm.model.Chr1.6 XP_008646117.1
> head(gene2go)
               GID         GO EVIDENCE
1 evm.model.Chr1.1 GO:0003677      EVA
2 evm.model.Chr1.1 GO:0003678      EVA
3 evm.model.Chr1.1 GO:0005524      EVA
4 evm.model.Chr1.1 GO:0016787      EVA
5 evm.model.Chr1.2 GO:0006520      EVA
6 evm.model.Chr1.2 GO:0016491      EVA
> head(koterms)
                GID     KO
1  evm.model.Chr1.1 K03657
2  evm.model.Chr1.2 K00261
3  evm.model.Chr1.6 K00759
4  evm.model.Chr1.7 K22534
5  evm.model.Chr1.9 K13783
6 evm.model.Chr1.11 K01051

**Comment by jmacdon** [comment]
We have a support site at support.bioconductor.org that is more appropriate for this sort of question. In future please post this sort of question there, rather than on this GitHub repo.

The quick answer is that you have missing data in your gene_info file, in the second column. Which is what the error is telling you when it says that the NOT NULL constraint on gene_info.GENENAME is failing. In other words, there is a constraint that the GENENAME cannot be NULL (SQL term for missing), and you are failing that constraint. Filter your gene_info table and you should be fine.

**Comment by C2051** [comment]
Thank you very much indeed！
