### ISSUE TITLE
Annotation database not working with topGO

### ISSUE THREAD

**Issue by felixlaguna** [Bioconductor/AnnotationForge#6]
When creating an annotation database like in the vignette:
```
makeOrgPackage(gene_info=fSym, chromosome=fChr, go=fGO,
               version="0.1",
               maintainer="bla",
               author="bla",
               outputDir = ".",
               tax_id="559292",
               genus="Saccharomyces",
               species="cerevisiae",
               goTable="go")
```
The package is generated, it is imported without a problem, but then it fails to be used with topGO, with the error of "missing table: go_cc":

```
install.packages("./org.Scerevisiae.eg.db",repos = NULL)
library("org.Scerevisiae.eg.db")
GODefault <- new("topGOdata",
                    description = "Simple session",
                    ontology = "CC",
                    allGenes = geneListOwn,
                    annot = annFUN.org,
                    mapping = "org.Scerevisiae.eg.db"
                 )
```

**Comment by dvantwisk** [comment]
Apologies for the delay.

First off, I'm not sure sure what the values of `fSym`, `fChar`, and `fGO` are in your example. I am assuming these values are from the `MakingNewOrganismPackages` vignette, however, these tables are for the zebra finch and not applicable to building a yeast orgdb package so the resulting package is not going to be useful.

You are right in pointing out that the user-generate orgdb packages do not include the `go_cc` table (among other `go_` tables it was missing). We found that the `org.Sc.sgd.db` that we maintain does contain these tables, so one option may be to use this package instead of generating a new one.

We have pushed changes to the master (devel) branch of AnnotationForge that will create the needed `go_` tables in user generated orgdb packages, so the package you build should now work with topGO.
